version: '3.5'
services:
  reader:
    container_name: reader
    image: reader:latest
    entrypoint: cargo run
    restart: on-failure
    environment:
      - PROCESSOR_QUANTITY=${TOTAL_PROCESSORS}
      - LOG_LEVEL=INFO
      - RABBITMQ_ADDR=amqp://guest:guest@rabbitmq:5672
      - PROCESSOR_QUEUE=reader_q
      - PROCESSOR_PLACES_QUEUE=reader_places_q
    volumes:
      - ./reader/data:/data
    networks:
      - test-network      

networks:
  test-network:
    external:
      name: ${SERVER_NAME}-network