version: '3.5'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - 15672:15672
    networks:
      - test-network

  processor:
    container_name: processor
    image: processor:latest
    entrypoint: cargo run
    restart: on-failure
    environment:
      - RABBITMQ_ADDR=amqp://guest:guest@rabbitmq:5672
      - LOG_LEVEL=INFO
      - READER_QUEUE=reader_q
      - READER_PLACES_QUEUE=reader_places_q
      - QUEUE_MAP=map_city
      - QUEUE_DATE=date_redirector_worker
      - QUEUE_COUNT=count_controller_worker
      - EOF_MAP=count_controller_worker
      - EOF_MAP=eof_map
      - EOF_COUNT=eof_count
      - EOF_DATE=eof_date
      - TOPIC_PLACES=places
    depends_on:
      - rabbitmq
    networks:
      - test-network

  map_master_controller:
    container_name: map_master_controller
    image: master_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=eof_map
      - SEND_QUEUE=map_city
      - TOTAL_WORKERS=${TOTAL_MAP_WORKERS}
    networks:
      - test-network

  map_worker:  
    image: map_worker:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=map_city
      - SEND_QUEUE=cities_resume
      - MASTER_SEND_QUEUE=master_map
      - TOPIC_PLACES=places
    networks:
      - test-network
        
  cities_resume1:  
    container_name: cities_resume1
    image: cities_resume:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=cities_resume
      - SEND_QUEUE=top_cities
      - MASTER_SEND_QUEUE=resume_master
    networks:
      - test-network
  
  resume_master_controller:  
    container_name: resume_master_controller
    image: resume_master_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=master_map
      - SEND_QUEUE=cities_resume
      - TOTAL_WORKERS=${TOTAL_MAP_WORKERS}
    networks:
      - test-network
  
  #resume_master_controller2:  
  #  container_name: resume_master_controller2
  #  image: resume_master_controller:latest
  #  entrypoint: python3 /main.py
  #  restart: on-failure
  #  depends_on:
  #    - rabbitmq
  #  links: 
  #    - rabbitmq
  #  environment:
  #    - PYTHONUNBUFFERED=1
  #    - RECV_QUEUE=resume_master
  #    - SEND_QUEUE=top_cities
  #    - TOTAL_WORKERS=1

  top_cities_controller:  
    container_name: top_cities_controller
    image: top_cities_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=top_cities
      - SEND_QUEUE=summary_resume
      - TOTAL_WORKERS=1
    networks:
      - test-network
  
  summary_controller:  
    container_name: summary_controller
    image: summary_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=summary_resume
    volumes:
      - ./summary_controller/summary:/summary
    networks:
      - test-network
  
  date_redirector_master_controller:
    container_name: date_redirector_master_controller
    image: master_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=eof_date
      - SEND_QUEUE=date_redirector_worker
      - TOTAL_WORKERS=${TOTAL_DATE_WORKERS}
    networks:
      - test-network
  
  date_redirector_worker:  
    image: date_redirector_worker:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=date_redirector_worker
      - SEND_QUEUE=dates_resume
      - MASTER_SEND_QUEUE=master_date
    networks:
      - test-network
  
  resume_date_master_controller:  
    container_name: resume_date_master_controller
    image: resume_master_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=master_date
      - SEND_QUEUE=dates_resume
      - TOTAL_WORKERS=${TOTAL_DATE_WORKERS}
    networks:
      - test-network
  
  dates_resume1:  
    container_name: dates_resume1
    image: dates_resume:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=dates_resume
      - SEND_QUEUE=date_sorter
      - MASTER_SEND_QUEUE=resume_date_master
    networks:
      - test-network
  
  #resume_date_master_controller2:  
  #  container_name: resume_date_master_controller2
  #  image: resume_master_controller:latest
  #  entrypoint: python3 /main.py
  #  restart: on-failure
  #  depends_on:
  #    - rabbitmq
  #  links: 
  #    - rabbitmq
  #  environment:
  #    - PYTHONUNBUFFERED=1
  #    - RECV_QUEUE=resume_date_master
  #    - SEND_QUEUE=date_sorter
  #    - TOTAL_WORKERS=1

  date_sorter:  
    container_name: date_sorter
    image: date_sorter:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=date_sorter
      - SEND_QUEUE=summary_resume
      - TOTAL_WORKERS=1
    networks:
      - test-network
  
  count_master_controller:
    container_name: count_master_controller
    image: master_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=eof_count
      - SEND_QUEUE=count_controller_worker
      - TOTAL_WORKERS=${TOTAL_COUNT_WORKERS}
    networks:
      - test-network
  
  count_controller_worker:  
    image: count_controller_worker:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=count_controller_worker
      - SEND_QUEUE=count_summary
      - MASTER_SEND_QUEUE=master_count
    networks:
      - test-network
  
  resume_count_master_controller:  
    container_name: resume_count_master_controller
    image: resume_master_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=master_count
      - SEND_QUEUE=count_summary
      - TOTAL_WORKERS=${TOTAL_COUNT_WORKERS}
    networks:
      - test-network
  
  count_summary_controller:  
    container_name: count_summary_controller
    image: count_summary_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=count_summary
      - SEND_QUEUE=summary_resume
    networks:
      - test-network
   
networks:
  test-network:
    name: ${COMPOSE_PROJECT_NAME}-network