DATE_RESUMER_JAN_WORKER = "date_resumer_jan"
CITY_RESUMER_AM_WORKER = "city_resumer_am"
COUNT_RESUME_WORKER = "count_resume"
MAP_WORKER = "map_worker"
COUNT_WORKER = "count_worker"
DATE_WORKER = "date_worker"
MASTER_MAP_WORKER = "master_map_worker"
MASTER_DATE_WORKER = "master_date_worker"
MASTER_COUNT_WORKER = "master_count_worker"
DATE_SORTER_WORKER = "date_sorter"
TOP_CITIES_WORKER = "top_cities"
SUMMARY_WORKER = "summary_worker"
PLACE_MANAGER_WORKER = "place_manager"
PROCESSOR_WORKER = "processor_worker"
COORDINATOR_WORKER = "coordinator_manager"

WORKER_TYPES = [
    DATE_RESUMER_JAN_WORKER,
    CITY_RESUMER_AM_WORKER,
    COUNT_RESUME_WORKER,
    MAP_WORKER,
    COUNT_WORKER,
    DATE_WORKER,
    MASTER_MAP_WORKER,
    MASTER_DATE_WORKER,
    MASTER_COUNT_WORKER,
    DATE_SORTER_WORKER,
    TOP_CITIES_WORKER,
    SUMMARY_WORKER,
    PLACE_MANAGER_WORKER,
    PROCESSOR_WORKER,
    COORDINATOR_WORKER
]
